### ISSUE TITLE
Code freezing error

### ISSUE THREAD

**Issue by Iapetus-11** [jython234/PyRakLib#2]
Upon entering an invalid ip or ip which doesn't have a server on it, this code freezes. Is there a way to set a timeout or to kill the process?

```
server = "ipaddress"
ping = UNCONNECTED_PING()
ping.pingID = 1234
ping.encode()
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST,1)
s.sendto(ping.buffer, (server, 19132))
recvData = s.recvfrom(2048) #2048
pong = UNCONNECTED_PONG()
pong.buffer = recvData[0]
pong.decode()
serverInfo = pong.serverName
serverInfo = str(serverInfo)
```

**Comment by alejzeis** [comment]
Hi there. Is this your own code or is this somewhere in the library?

**Comment by Iapetus-11** [comment]
It's copied from the tests folder

**Comment by alejzeis** [comment]
It's freezing as it's waiting for a packet reply from the server, and if
there isn't a server running at that address it'll wait forever. This isn't
an issue with the library , it's just due to how sockets work.

I assume you're trying to build a client, so if you want to do a timeout
for waiting for a response you can use nonblocking recieve as described
here:
https://medium.com/vaidikkapoor/understanding-non-blocking-i-o-with-python-part-1-ec31a2e2db9b

The article is for a TCP socket, but the same will work and apply to UDP
using the "sock.setblocking()" method

**Comment by Iapetus-11** [comment]
Thank you so much!
